### PR TITLE
[CDAP-12897] Temporarily disable ORC plugin until hive explore issue is fixed

### PR DESCRIPTION
**Pull request by ecfm**
https://issues.cask.co/browse/CDAP-12897

### CODE REVIEW

**Comment by albertshau** [comment]
why bother removing it temporarily instead of just fixing it? Are we planning to remove it for a release? That will be a backwards incompatible change.

**Comment by ecfm** [comment]
@albertshau I can keep looking into it, but I'm not able to estimate how much more time it will take to fix it. It can be pushed to the market sooner by removing it. Otherwise, yes, we can push it until this is fixed.

**Comment by albertshau** [comment]
Is it already in market? If so, this will be a backwards incompatible update.

**Comment by ecfm** [comment]
@albertshau not yet

**Comment by albertshau** [comment]
I see. If you want to remove support for the orc plugin, you should remove orc entirely. Remove the class, remove the dependency, remove the export. Otherwise the jar will be bigger than it needs to be, and it will cause class conflicts with anything else that uses orc.

**Comment by albertshau** [comment]
you need to remove the dependency and the export in the pom.

**Review by albertshau — APPROVED** [review]
lgtm

**Pull request merged**
